export const productInformation = [
  {
    name: "name",
    type: "text",
    label: "Name",
    width: "411px",
    value: "NameName",
    required: true,
  },
  {
    name: "category",
    type: "text",
    label: "Category",
    width: "276px",
    value: "Wet Food",
    required: false,
  },
  {
    name: "brand",
    type: "text",
    label: "Brand",
    width: "276px",
    value: "E-mailE-mail",
    required: false,
  },
  {
    name: "notAvailable",
    type: "text",
    label: "Availability",
    width: "276px",
    value: "In stock",
    required: false,
  },
  {
    name: "price",
    type: "text",
    label: "Price per unit",
    width: "130px",
    value: "",
    required: false,
  },
  {
    name: "priceWithDiscount",
    type: "text",
    label: "Price on discount",
    width: "130px",
    value: "",
    required: false,
  },
  {
    name: "material",
    type: "text",
    label: "Material",
    width: "276px",
    value: "",
    required: false,
  },
  {
    name: "color",
    type: "text",
    label: "Color",
    width: "276px",
    value: "",
    required: false,
  },
  {
    name: "age",
    type: "text",
    label: "Age",
    width: "276px",
    value: "",
    required: false,
  },
  {
    name: "size",
    type: "text",
    label: "Size",
    width: "276px",
    value: "",
    required: false,
  },
  {
    name: "weight",
    type: "text",
    label: "Weight",
    width: "276px",
    value: "",
    required: false,
  },
  {
    type: "checkout",
  },
];

export const additionalInformation = [
  {
    name: "prescription",
    type: "text",
    label: "Prescription",
    width: "276px",
    value: "Liver desease Diabetes",
    required: false,
  },
  {
    name: "contraindications",
    type: "text",
    label: "Contraindications",
    width: "276px",
    value: "Sterelized Diabetes",
    required: false,
  },
  {
    name: "description",
    type: "text",
    label: "Description",
    width: "569px",
    value: "",
    required: false,
  },
  {
    name: "instruction",
    type: "text",
    label: "Instruction",
    width: "569px",
    value: "",
    required: false,
  },
];
