export const productInformation = [
  {
    name: "name",
    type: "text",
    label: "Name",
    width: "411px",
    required: true,
  },
  {
    name: "newArrival",
    label: "New arrivals",
    type: "checkout",
    width: '100px',
  },
  {
    name: "category",
    type: "select",
    label: "Category",
    width: "276px",
    required: true,
  },
  {
    name: "brand",
    type: "select",
    label: "Brand",
    width: "276px",
    required: false,
  },
  {
    name: "notAvailable",
    type: "select",
    label: "Availability",
    width: "276px",
    required: false,
  },
  {
    name: "price",
    type: "text",
    label: "Price per unit",
    width: "130px",
    required: true,
  },
  {
    name: "priceWithDiscount",
    type: "text",
    label: "Price on discount",
    width: "130px",
    required: false,
  },
  {
    name: "material",
    type: "select",
    label: "Material",
    width: "276px",
    required: false,
  },
  {
    name: "color",
    type: "select",
    label: "Color",
    width: "276px",
    required: false,
  },
  {
    name: "age",
    type: "select",
    label: "Age",
    width: "276px",
    required: false,
  },
  {
    name: "size",
    type: "select",
    label: "Size",
    width: "276px",
    required: false,
  },
  {
    name: "weight",
    type: "select",
    label: "Weight",
    width: "276px",
    required: false,
  },
  {
    name: "prescription",
    type: "select",
    label: "Prescription",
    width: "276px",
    required: false,
  },
];

export const additionalInformation = [
  {
    name: "contraindications",
    type: "textarea",
    label: "Contraindications",
    width: "569px",
    required: false,
  },
  {
    name: "description",
    type: "textarea",
    label: "Description",
    width: "569px",
    required: false,
  },
  {
    name: "instructions",
    type: "textarea",
    label: "Instruction",
    width: "569px",
    required: false,
  },
];